### ISSUE TITLE
How is this library used? (Add documentation)

### ISSUE THREAD

**Issue by ibuilder** [EtienneLamoureux/php-json-iterator#1]
Do you have a test or usage case on how to use this?

**Comment by EtienneLamoureux** [comment]
Yes, I should be able to work on documentation, tests and examples pretty soon.

**Comment by rogeriotaques** [comment]
Anywhere the documentation can be found?

**Comment by EtienneLamoureux** [comment]
@rogeriotaques

This is an old project, but I'll try to publish some documentation later today.

In the meantime, you can see it used [here](https://github.com/EtienneLamoureux/durmand-scriptorium/blob/master/src/Consumer.php#L98).
- If your JSON objects are flat (with no nested JSON objects), you can construct the iterators without any options.
- If your JSON objects contain nested objects, you need to pass in `firstTopLevelString` equal to the first key of the top-level object. For example, if you have the following:
```json
[
	{
		"foo": 1,
		"bar": {
			"fizz": "buzz"
		}
	},
	{
		"foo": 2,
		"bar": {
			"fizz": "buzz"
		}
	},
	{
		"foo": 3,
		"bar": {
			"fizz": "buzz"
		}
	},
	{
		"foo": 4,
		"bar": {
			"fizz": "buzz"
		}
	}
]
```
In this case, the value of `firstTopLevelString` should be set to `foo`. Also, since you're passing the square brackets of the JSON array, `jsonHasSquareBrackets` should be set to `true`.

Once the iterator is built, you can use it like [any other vanilla PHP iterator](https://www.php.net/manual/en/class.iterator.php), which will give you [JSON decoded PHP arrays](https://www.php.net/manual/en/function.json-decode.php).

**Comment by rogeriotaques** [comment]
Tks @EtienneLamoureux ! Will check it out.

How big can be the JSON? I'm looking for a better way to work with a (nested) JSON data with over 16k records. Each record (in the top-level) have other lists of records (maybe dozens which are also nested objects) .. so the final amount of objects are huge.

**Comment by EtienneLamoureux** [comment]
As big as you want!
To be precise, it depends how much memory you can work with (as json_decode balloons up quite rapidly) but, if you can fit one record comfortably in memory, the current release of the iterator will parse it all, no matter the size, one record at a time. You may have to store the full JSON in temporary files (reading from files is also supported by this project).

**Comment by EtienneLamoureux** [comment]
I fixed some issues, packaged a [new release](https://github.com/EtienneLamoureux/php-json-iterator/releases/tag/1.0.0) and added [tests](https://github.com/EtienneLamoureux/php-json-iterator/blob/master/tests/Iterators/JsonIteratorTest.php) as example usage.
